from __future__ import annotations

from typing import Protocol
from uuid import UUID

from .project import Project


class ProjectRepository(Protocol):
    def save(self, project: Project) -> Project: ...

    def get_by_id(self, project_id: UUID) -> Project | None: ...

    def list_all(self) -> list[Project]: ...

    def delete(self, project_id: UUID) -> None: ...

    def add_content(self, project_id: UUID, content_id: UUID) -> None: ...

    def remove_content(self, project_id: UUID, content_id: UUID) -> None: ...

    def list_content_ids(self, project_id: UUID) -> list[UUID]: ...
